#!/usr/bin/env python3
"""Bundle the dashboard UI source into the firmware's web_ui.h.

The editable source lives here in ui/:
    index.html      - markup + CSS, loads airbox-app.js via <script src=...>
    airbox-app.js   - dashboard logic (vanilla JS)

This inlines airbox-app.js into index.html, gzip-compresses the result, and
writes it as the INDEX_HTML_GZ byte array in firmware/airbox/web_ui.h (between
the GENERATED markers). The firmware serves it with `Content-Encoding: gzip`,
zero-copy from flash — small on the wire and easy on the heap, which is what
keeps the dashboard from stalling on a weak link. PORTAL_HTML and the rest of
web_ui.h are left untouched.

Workflow:
    1. Edit ui/index.html / ui/airbox-app.js (open index.html in a browser to
       preview; it falls back to mock data when there's no device).
    2. python3 ui/build-web-ui.py
    3. Recompile / flash the firmware.

No external tools or packages required (standard library only).
"""
import gzip
import re
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
WEBUI = ROOT / "firmware" / "airbox" / "web_ui.h"
SCRIPT_TAG = '<script src="airbox-app.js"></script>'
BEGIN = "// >>> GENERATED BY ui/build-web-ui.py — DO NOT EDIT BELOW >>>"
END = "// <<< END GENERATED <<<"


def to_c_array(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + ",".join("0x%02x" % b for b in chunk) + ",")
    return "\n".join(lines)


def main():
    html = (HERE / "index.html").read_text()
    js = (HERE / "airbox-app.js").read_text()

    if SCRIPT_TAG not in html:
        raise SystemExit(f"index.html must contain exactly: {SCRIPT_TAG}")
    bundled = html.replace(SCRIPT_TAG, "<script>\n" + js.rstrip("\n") + "\n</script>")
    raw = bundled.encode("utf-8")

    # mtime=0 keeps the output byte-for-byte reproducible across rebuilds.
    gz = gzip.compress(raw, compresslevel=9, mtime=0)

    block = (
        BEGIN + "\n"
        "const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n"
        + to_c_array(gz) + "\n"
        "};\n"
        "const size_t INDEX_HTML_GZ_LEN = sizeof(INDEX_HTML_GZ);\n"
        + END
    )

    webui = WEBUI.read_text()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pat.search(webui):
        raise SystemExit(
            f"GENERATED markers not found in web_ui.h; expected:\n  {BEGIN}\n  ...\n  {END}"
        )
    new = pat.sub(lambda m: block, webui, count=1)

    WEBUI.write_text(new)
    print(f"web_ui.h INDEX_HTML_GZ updated: {len(raw):,} B HTML "
          f"-> {len(gz):,} B gzip ({len(gz)/1024:.1f} KB, "
          f"{100 - len(gz) * 100 // len(raw)}% smaller)")


if __name__ == "__main__":
    main()
